version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - "./app:/code/app"
      - ".env:/code/.env"
      - "./fixtures/resume.txt:/code/fixtures/resume.txt"
      - "./fixtures/chatbot.db:/code/fixtures/chatbot.db"
